### ISSUE TITLE
Create SecureBankingAcceleratorToolkit.github.io web site

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit#10]
## Story

As a developer I want to create a website so that the customer have one place to consult all related with the Secure Banking Accelerator Toolkit source.

## Acceptance criteria

- Public Secure Banking Accelerator Toolkit web site hosted by github.

## Tasks
- [x] Agree what needs to be on the site
- [x] Create wireframes
- [x] Create `SecureBankingAcceleratorToolkit` web site using github.io

### Release Notes

Affected App: Documentation and contents.

**Comment by BohoCode** [comment]
This issue need a lot more in the way of requirements before we can start on it. It maybe that we should put this documentation on the foregerock developer site. Need to discuss with management before we make any firm decisions.

**Comment by jorgesanchezperez** [comment]
Done
